name: CI for angular app
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACS_ID }}
          aws-secret-access-key: ${{ secrets.ACS_PASS }}
          aws-region: us-east-1

      - uses: actions/checkout@v2
      - name: Use Node.js 16.15.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.16.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Build
        run: npm run build:prod

      - name: Deploy to S3
        if: success()
        run: |
          aws s3 sync ./dist/ci-testing-angular s3://${{ secrets.BUCKET_NAME }}
